### PR TITLE
Ignore "Missing config file..." during save if "save-commands.json" is not found in path.

### PR DESCRIPTION
**Pull request by flplv**
This handles issue #30.

### CODE REVIEW

**Comment by mvila** [comment]
:+1:

**Comment by dkapanidis** [comment]
any news on this? I also had the same error.

**Comment by benadamstyles** [comment]
@JsonHunt can we get this merged? Any way I can help? Thanks!

**Review by pixilz — APPROVED** [review]

**Review by pixilz — COMMENTED** [review]
Can we merge this.

**Comment by setage** [comment]
Also, fixes #42 and #38 

Merge, please! This is very annoying!

**Comment by mvila** [comment]
Since this repository has been abandoned by his author, I created a plugin doing the same thing with a simpler interface: https://github.com/mvila/on-save

**Pull request merged**
