### PR TITLE
Fix find() issue

### LINKED ISSUE #25: Uncaught TypeError: atom.views.getView(...).find is not a function
[Enter steps to reproduce below:]
1. Edit a file
2. Hit Save

**Atom Version**: 1.0.19
**System**: Mac OS X 10.11
**Thrown From**: [save-commands](https://github.com/JsonHunt/save-commands) package, v0.6.2
### Stack Trace

Uncaught TypeError: atom.views.getView(...).find is not a function

```
At /Users/ewout/.atom/packages/save-commands/lib/atom-save-commands.coffee:107

TypeError: atom.views.getView(...).find is not a function
  at Object.module.exports.AtomSaveCommands.executeCommand (/Users/ewout/.atom/packages/save-commands/lib/atom-save-commands.coffee:107:44)
  at iterate (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/request/node_modules/form-data/node_modules/async/lib/async.js:146:13)
  at Object.async.eachSeries (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/request/node_modules/form-data/node_modules/async/lib/async.js:162:9)
  at /Users/ewout/.atom/packages/save-commands/lib/atom-save-commands.coffee:259:12
  at /Users/ewout/.atom/packages/save-commands/lib/atom-save-commands.coffee:276:5
  at FSReqWrap.oncomplete (fs.js:82:15)

```
### Commands

```
     -1:33.7.0 core:move-up (atom-text-editor.editor.is-focused)
     -1:33.3.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:32.3.0 core:save (atom-text-editor.editor.is-focused)
  3x -0:57.7.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:46.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:45 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -0:44.8.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:43.7.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:43.4.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -0:42.6.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
  3x -0:40.8.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:39.9.0 core:save (atom-text-editor.editor.is-focused)
     -0:33.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:32.8.0 core:save (atom-text-editor.editor.is-focused)
     -0:02.6.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:01.2.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ],
    "packagesWithKeymapsDisabled": [
      "highlight-line"
    ],
    "openEmptyEditorOnStart": false,
    "disabledPackages": [
      "tree-view-git-projects"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.28.14
atom-import-sort, v0.5.0
file-icons, v1.6.11
git-log, v0.4.1
go-plus, v3.5.1
highlight-line, v0.11.0
highlight-selected, v0.10.1
language-hcl, v0.1.2
minimap, v4.13.4
minimap-highlight-selected, v4.3.1
open-recent, v2.3.0
project-manager, v2.6.5
save-commands, v0.6.2
tree-view-git-status, v0.2.2

# Dev
No dev packages
```

### PR DESCRIPTION
**Pull request by FranckKe**
Got the fix from #24 and its fork https://github.com/jacobrs/save-commands
All credits goes to @jacobrs. Let me know if you want to do your own PR, I figured you were busy and did it myself.
Fix #25

### CODE REVIEW

**Comment by jacobrs** [comment]
@FranckKe I have been quite busy lately and completely forgot to do this, thanks for doing it!

**Comment by tv-brendan-jefferis** [comment]
This change has not been included in the latest version of the official package (installed via Atom).

In the meantime, I've manually edited the code myself but it'd be great to see this go out!

**Comment by PaulCapestany** [comment]
+1

**Comment by chikamichi** [comment]
It could be nice releasing this fix :monkey_face:

**Pull request merged**
